<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Paperdoll.Core\Paperdoll.Core.csproj" />
  </ItemGroup>
</Project>
