<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Paperdoll</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Simple" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\icon.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Paperdoll.Core\Paperdoll.Core.csproj" />
  </ItemGroup>
</Project>
